name: Build iOS

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Install Rosetta 2
        run: sudo softwareupdate --install-rosetta --agree-to-license

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.5' 

      - name: Check Flutter version
        run: flutter --version

      - name: Install Flutter dependencies
        run: flutter pub get

      - name: Check Xcode Version
        run: xcodebuild -version

      - name: Create keychain
        run: |
          security create-keychain -p "$KEYCHAIN_PASSWORD" build.keychain
          security import <(echo "$CERTIFICATE_P12" | base64 --decode) -k build.keychain -P "$CERTIFICATE_PASSWORD" -T /usr/bin/codesign
          security set-key-partition-list -S apple-tool:,apple: -s -k "$KEYCHAIN_PASSWORD" build.keychain
          security unlock-keychain -p "$KEYCHAIN_PASSWORD" build.keychain
        env:
          CERTIFICATE_P12: ${{ secrets.CERTIFICATE_P12 }}
          CERTIFICATE_PASSWORD: ${{ secrets.CERTIFICATE_PASSWORD }}
          KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}

      - name: Set up provisioning profile
        run: |
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          echo "$PROVISIONING_PROFILE" | base64 --decode > ~/Library/MobileDevice/Provisioning\ Profiles/App.mobileprovision
        env:
          PROVISIONING_PROFILE: ${{ secrets.PROVISIONING_PROFILE }}

      - name: Build iOS app
        run: flutter build ios --release --no-codesign

      - name: Export .ipa
        run: |
          xcodebuild \
            -exportArchive \
            -archivePath build/ios/archive/Runner.xcarchive \
            -exportPath build/ios/ipa \
            -exportOptionsPlist ios/exportOptions.plist
