name: Build iOS

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Install Rosetta 2
        run: sudo softwareupdate --install-rosetta --agree-to-license

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.5' 

      - name: Check Flutter version
        run: flutter --version

      - name: Install Flutter dependencies
        run: flutter pub get

      - name: Build iOS app
        run: flutter build ios --release --no-codesign

      - name: Archive the app using xcodebuild
        run: |
          xcodebuild \
            -workspace ios/Runner.xcworkspace \
            -scheme Runner \
            -sdk iphoneos \
            -configuration Release \
            -archivePath build/ios/archive/Runner.xcarchive \
            clean archive \
            CODE_SIGN_STYLE=Automatic

      - name: Check if archive exists
        run: |
          if [ ! -d "build/ios/archive/Runner.xcarchive" ]; then
            echo "Archive not found! Exiting..."
            exit 1
          fi

      - name: Export .ipa
        run: |
          xcodebuild \
            -exportArchive \
            -archivePath build/ios/archive/Runner.xcarchive \
            -exportPath build/ios/ipa \
            -exportOptionsPlist ios/exportOptions.plist
